### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#11]
Logo BET alligné à gauche
Menu 
- Parcours
- Progression personnelle
- Halte
- Espace Ecoute
- Progression générale
- Forum
Icone d'espace personnel

![01_Master Screen – 1](https://user-images.githubusercontent.com/62614774/77481070-31678500-6e23-11ea-976c-e8130d18e0f4.png)

**Comment by guiyom-e** [comment]
Il manque  Icone d'espace personnel
Il y a un bouton Se connecter en plus.

**Comment by thomasgall67** [comment]
![icons8-test-account-96](https://user-images.githubusercontent.com/62614774/78695690-b4e2a500-78fe-11ea-95a9-e7db2f8e0c4a.png)

**Comment by guiyom-e** [comment]
Forum -> supprimer
Espace écoute -> Espace précention

Pour les chefs:
Validation d'activités
Activités de mes jeunes
Progression Générale
Halte/Nuage de mots
Espace prévention

Pour le relecteur
La même chose sauf progression des jeunes

Admin:
comme chef, mais vois toutes les activités
