### ISSUE TITLE
Espace Personnel

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#12]
Click sur icone "Espace Personnel"
Bouton : Se déconnecter ==> Retour sur Connexion View

**Comment by victorfau** [comment]
Quels sont les champs présent dans cette page 
- nom
- prenom
- groupe
- Territoire ?

**Comment by thomasgall67** [comment]
Non y'a pas de champ, je pense que juste un bouton déconnexion ira ?
Ou alors un bouton "Help" qui fait un mailto ?

**Comment by victorfau** [comment]
Va pour le bouton de déco, si ils ont besoin d'aide, ils passent par le chefs qui nous font un mail ?

**Comment by thomasgall67** [comment]
Ouais aussi. Au plus simple pour ca !

**Comment by guiyom-e** [comment]
On ne fait plus d'espace personnel
