### ISSUE TITLE
Quitter une relecture en cours de route : pas possible d'y retourner

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#131]
Choisir une relecture
Fermer page
Revenir sur Activités à valider
Relecture n'est plus présenter

**Comment by nd4pa** [comment]
l'API est ready, des qu'un relecteur update son code est lier a la progression, et la liste des progressions renvoie les progression en "FINISHED" a tout les relecteur et les progressions "REVIEWING" lie a l'utilisateur qui fait le relecture
