### ISSUE TITLE
possibilité changer parcours si déco/reco

### ISSUE THREAD

**Issue by JacquesDhuesme** [bet3-0/b3t#137]
On peux changer de parcours si on se deconnecte.
J'ai pas acces à ma progression de mon ancien parcours si je change. Par contre je peux me déconnecter, reco, changer de parcours à nouveau et je récupère ma progression

**Comment by guiyom-e** [comment]
Est-ce que c'est toujours le cas ?

Est-ce que tu peux me dire les étapes pour y arriver ?
Je pense qu'il doit y avoir une erreur dans la console qui fait que ça by-pass une étape ?

**Comment by JacquesDhuesme** [comment]
je test et je te dis

**Comment by JacquesDhuesme** [comment]
Oui c'est le cas. Tu te connecte, choisis un parcours, déco, reco et tu peux rechoisir un parcours différent
