### ISSUE TITLE
Rendu d'une activité

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#20]
A la dernière page de l'activité, l'utilisateur peut téléverser un fichier (img, video, texte, pdf, word....)
Puis cliquer sur valider 
* Redirige vers résumé de l'activité #21
* Activité passe en statut "En cours de vérification" #22

![06_Activité](https://user-images.githubusercontent.com/62614774/77527359-43314280-6e8c-11ea-9f5c-ef80b012c8de.png)

**Comment by guiyom-e** [comment]
ça c'est inclu dans une activité, donc on peut clore l'issue je pense.
les rendus peuvent être intermédiaires
