### ISSUE TITLE
Resumé d'une activité

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#21]
L'utilisateur peut voir le résumé de son activité avec validation

Il peut télécharger son rendu et vérifier le statut de son activité

Il peut ensuite choisir de continuer son parcours en cliquant sur le bouton "Continuer mon parcours" ==> Retour sur Catalogue

![07_Résumé Activité](https://user-images.githubusercontent.com/62614774/77527689-eaae7500-6e8c-11ea-82d7-5b7194a1fb39.png)

**Comment by guiyom-e** [comment]
On garde ça ?
Le seul intérêt d'une page, c'est de pouvoir télécharger son rendu... mais ça sera forcément un truc dégueu (sauf si on fait des beaux modules pour transformer la progression en PDF, pas encore à l'ordre du jour !)

Si on fait juste une vérification quand on appuie sur le bouton valider de la dernière page, c'est suffisant ou pas ?

**Comment by thomasgall67** [comment]
Non on supprime :) Ca servira pas je pense
