### ISSUE TITLE
Listes des activités à valider

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#24]
Liste des activités terminées et non validées
Filtre par parcours / activité (?)
Click sur activité ==> Modale de validation #25

![09_Vue Validation](https://user-images.githubusercontent.com/62614774/77564579-3e3bb580-6ec3-11ea-8414-863c951b6dd5.png)

**Comment by guiyom-e** [comment]
Niveau droits utilisateurs c'st géré comment ?
Tous les chefs correcteurs ont accès à toutes les fiches et trient à la main ?
Est-ce que la BDD pourra gérer des droits à ce niveau là ?

Pour commencer, je pars du principe que le back renvoie la bonne liste des activités autorisées et on peut faire un filtre sur parcours et identifiant.

**Comment by guiyom-e** [comment]
C'est bien Progression Générale le bouton de la nav bar pour accéder à cette page ? Bouton accessible uniquement si on a le bon rôle ?

**Comment by guiyom-e** [comment]
Dansles colonnes, je mettrais : nom d'activité, identifiant, durée (réelle = finishedAt-startedAt)
le nom d'activité est de la couleur du parcous

**Comment by thomasgall67** [comment]
Alors y'a 2 choses
* Une page de validation des activités accessible par les admins et les modérateurs (correcteurs) avec toutes les activités à filtrer par Parcours
* Une page orientée structure pour les chefs où ils ont la barre de progression de leurs jeunes (et d'autres infos à définir) et là on affiche le numéro d'adhérent. 

Progression générale devrait permettre à chaque jeune de retrouver les rendus de ses parcours. On s'est pas bcp avancé là dessus
