### ISSUE TITLE
Modale de validation

### ISSUE THREAD

**Issue by thomasgall67** [bet3-0/b3t#25]
Titre de l'activité
2 bouttons
    * Accepter ==> Vérification si activité toujours disponible ==> Assignation de la vérification à l'utilisateur courant ==> Activité disparait de la liste ==> Redirection sur la validation de l'activité #26
     * Retour ==> Retour page des activités à valider

Penser à vérifier qu'entre le moment ou l'activité été choisie par l'équipier et le moment où il clique sur le bouton "Accepter",  l'activité n'a pas été "acceptée" 
Comment gérer le cas (rare) où l'activité est "acceptée" par 2 utilisateurs en même temps ?
Comment la liste se met-elle à jour ? Dynamiquement ou il faut recharger la page ?

![010_aVue Validation – 1](https://user-images.githubusercontent.com/62614774/77565181-24e73900-6ec4-11ea-86de-9913804a5270.png)

**Comment by guiyom-e** [comment]
Penser à vérifier qu'entre le moment ou l'activité été choisie par l'équipier et le moment où il clique sur le bouton "Accepter", l'activité n'a pas été "acceptée"  --> pas fait

 Dynamiquement ou il faut recharger la page ? -> bouton Mettre à jour
